import os

PROJECT_NAME = "autovp"
SOURCE_DIRECTORY = os.path.join(ENTER DIRECTORY HERE)
MAIN_DIRECTORY = os.path.join(SOURCE_DIRECTORY, PROJECT_NAME)
VENV_DIRECTORY = os.path.join(SOURCE_DIRECTORY, ".venv")
PROJECT_DIRECTORY = os.path.join(MAIN_DIRECTORY, PROJECT_NAME)